name = "vendflare"
main = "dist/worker.js"
compatibility_date = "2024-09-02"

workers_dev = false
send_metrics = false
keep_vars = true

[build]
command = "tsx build.ts"

[[kv_namespaces]]
binding = "KV"
id = "b6aa428038974b3b825ef772b01a33b1"

# [[durable_objects.bindings]]
# name = "USER_DATA"
# class_name = "UserData"

[observability]
enabled = true
