name = "vendflare"
main = "src/worker.ts"
compatibility_date = "2023-05-30"

workers_dev = false
send_metrics = false
keep_vars = true

[[durable_objects.bindings]]
name = "USER_DATA"
class_name = "UserData"
