name = "vendflare"
main = "dist/index.js"
compatibility_date = "2025-03-19"

workers_dev = false
send_metrics = false
keep_vars = true
no_bundle = true

[build]
command = "node build.ts"

[[d1_databases]]
binding = "DB"
database_name = "vendflare"
database_id = "e30acede-0d23-4e95-8cb1-9d570099d3ac"

[observability]
enabled = true
