name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@078e9d416474b29c0c387560859308974f7e9c53 # ratchet:pnpm/action-setup@v6.0.1
      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # ratchet:actions/setup-node@v6
        with:
          node-version-file: .node-version
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint -f @microsoft/eslint-formatter-sarif -o /tmp/lint.sarif
        continue-on-error: true

      - name: Strip suppressed results
        run: pnpm dlx @ryanccn/sarif-strip-suppressed /tmp/lint.sarif

      - name: Upload results
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # ratchet:github/codeql-action/upload-sarif@v4.35.2
        with:
          sarif_file: /tmp/lint.sarif
          wait-for-processing: true
