name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # ratchet:actions/checkout@v6

      - name: Setup and install dependencies
        uses: pnpm/setup@fbda4c85fc2e1e08721cd8763afea8f48d60f024 # ratchet:pnpm/setup@v2
        with:
          cache: true

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint -f @microsoft/eslint-formatter-sarif -o /tmp/lint.sarif
        continue-on-error: true

      - name: Strip suppressed results
        run: pnpm dlx @ryanccn/sarif-strip-suppressed /tmp/lint.sarif

      - name: Upload results
        uses: github/codeql-action/upload-sarif@2892aa5e19bbd11bc0cff5427e3b750a04d9e3c2 # ratchet:github/codeql-action/upload-sarif@v4.38.2
        with:
          sarif_file: /tmp/lint.sarif
          wait-for-processing: true
