name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read
  security-events: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # ratchet:actions/checkout@v6

      - name: Setup and install dependencies
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # ratchet:pnpm/setup@v2
        with:
          cache: true

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint -f @microsoft/eslint-formatter-sarif -o /tmp/lint.sarif
        continue-on-error: true

      - name: Strip suppressed results
        run: pnpm dlx @ryanccn/sarif-strip-suppressed /tmp/lint.sarif

      - name: Upload results
        uses: github/codeql-action/upload-sarif@7211b7c8077ea37d8641b6271f6a365a22a5fbfa # ratchet:github/codeql-action/upload-sarif@v4.36.0
        with:
          sarif_file: /tmp/lint.sarif
          wait-for-processing: true
